version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: 'marketplace'
    command: 'python manage.py runserver 0.0.0.0:8000'
    environment:
      - DATABASE_HOST=postgres
    env_file:
      - ./marketplace/.env
    volumes:
        - .:/marketplace
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  celery:
      build: .
      container_name: 'celery'
      command: celery -A marketplace worker -l info
      volumes:
        - .:/marketplace
      links:
        - redis
      depends_on:
        - web
        - redis

volumes:
    postgres-volume: