version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    restart: always
    container_name: 'marketplace'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/marketplace
    ports:
      - '8000:8000'
  celery:
      build: .
      container_name: 'celery'
      command: celery -A marketplace worker -l info
      volumes:
        - .:/marketplace
      links:
        - redis
      depends_on:
        - web
        - redis